### ISSUE TITLE
Changing protocol scheme in settings menu does not update

### ISSUE THREAD

**Issue by jrozner** [theparanoids/aterm#17]
**Golang version** (`go version`): 1.14.9

**OS version** (`uname -a` if on a Unix-like system): macos 10.15.6

**Description of the problem including expected versus actual behavior**:

Going through the first run and then attempting to change the protocol used (eg. https -> http) for the api url does not update. If a user enters the wrong one when setting up they need to exit the application and change it.

**Steps to reproduce**:

 1. Start aterm and walk through the setup process using https://localhost:3000
 2. Update config from menus and change from https://localhost:3000 to http://localhost:3000
 3. Attempt to test the connnection

**Comment by JoelAtDeluxe** [comment]
I think each of the edited values are not being saved.
