### ISSUE TITLE
Shell isn't set during setup

### ISSUE THREAD

**Issue by jrozner** [theparanoids/aterm#33]
When the automatic setup runs the shell isn't set. This is present in the current release. Untested in master.

**Comment by JoelAtDeluxe** [comment]
This seems to be fixed in master. Here's what I tested

fresh start => always chooses `$SHELL` This seems to save properly in both version 
update settings => this seems to omit saving, or saves an empty string. But, this seems to work on master.

**Comment by jrozner** [comment]
Ah perfect. We should just cut a new release to get the fix then. I'll go ahead and close this.
